### ISSUE TITLE
`venv-update` appears to be trying to install packages every run

### ISSUE THREAD

**Issue by Asday** [tox-dev/tox-pip-extensions#13]
When installing this, I expected some manner of env update step to be run if my requirements differed from the previous run, but what appears to be happening instead is the env update step is running on _every_ test run, relying on `pip` (I think) to "quickly" determine that the environment matches the requirements, significantly slowing down the process.

Was my expectation incorrect?  Or is my configuration incorrect?

Below I've included my `tox.ini`, and the output of a typical `detox` run, demonstrating the issue, followed by the output of a typical `detox` run without `tox_pip_extensions_ext_venv_update = true` in the configuration.  Of note is an `AssertionError` in the `detox` run with the extension active, which isn't present otherwise.

`tox.ini`:

```ini
[tox]
envlist = py36,py37
tox_pip_extensions_ext_venv_update = true
[testenv]
deps =
  -rrequirements-dev.txt
commands = pytest
setenv =
  PYTHONPATH={toxinidir}/tests
  PYTHONUNBUFFERED=yes
[flake8]
exclude=
  # Protobuf generated files
  *_pb2.py
  # Django migration folders
  migrations
  # Site-packages and friends
  env
  .tox
[pytest]
python_paths = src/keiyakusha
DJANGO_SETTINGS_MODULE = config.settings
django_find_project = false
```

`detox` output with extension enabled:

```
GLOB sdist-make: /home/asday/code/src/github.com/asday/keiyakusha/setup.py
py36 inst-nodeps: /home/asday/code/src/github.com/asday/keiyakusha/.tox/dist/keiyakusha-0.0.0.zip
py37 inst-nodeps: /home/asday/code/src/github.com/asday/keiyakusha/.tox/dist/keiyakusha-0.0.0.zip
py37 bootstrap: venv-update>=2.1.3
py36 bootstrap: venv-update>=2.1.3
Traceback (most recent call last):
  File "/home/asday/code/src/github.com/asday/keiyakusha/env/lib/python3.7/site-packages/eventlet/hubs/hub.py", line 460, in fire_timers
    timer()
  File "/home/asday/code/src/github.com/asday/keiyakusha/env/lib/python3.7/site-packages/eventlet/hubs/timer.py", line 59, in __call__
    cb(*args, **kw)
  File "/home/asday/code/src/github.com/asday/keiyakusha/env/lib/python3.7/site-packages/detox/proc.py", line 66, in _loopreport
    assert not ac2popenlist, ac2popenlist
AssertionError: {'bootstrap': [<eventlet.green.subprocess.Popen object at 0x7fbbf7575208>, <eventlet.green.subprocess.Popen object at 0x7fbbf7575c50>]}
GLOB sdist-make: /home/asday/code/src/github.com/asday/keiyakusha/setup.py
GLOB sdist-make: /home/asday/code/src/github.com/asday/keiyakusha/setup.py
py37 installdeps: -rrequirements-dev.txt
py36 installdeps: -rrequirements-dev.txt
py37 installed: argh==0.26.2,atomicwrites==1.1.5,attrs==18.1.0,detox==0.12,Django==2.1,django-widget-tweaks==1.4.2,dnspython==1.15.0,eventlet==0.24.1,flake8==3.5.0,greenlet==0.4.14,keiyakusha==0.0.0,mccabe==0.6.1,monotonic==1.5,more-itertools==4.3.0,pathtools==0.1.2,pluggy==0.7.1,py==1.5.4,pycodestyle==2.3.1,pyflakes==1.6.0,pytest==3.7.1,pytest-django==3.4.1,pytest-pythonpath==0.7.2,pytz==2018.5,PyYAML==3.13,six==1.11.0,tox==3.2.1,tox-pip-extensions==1.3.0,unicode-slugify==0.1.3,Unidecode==1.0.22,venv-update==3.1.0,virtualenv==16.0.0,watchdog==0.8.3
py37 runtests: PYTHONHASHSEED='785840529'
py37 runtests: commands[0] | pytest
py36 installed: argh==0.26.2,atomicwrites==1.1.5,attrs==18.1.0,detox==0.12,Django==2.1,django-widget-tweaks==1.4.2,dnspython==1.15.0,eventlet==0.24.1,flake8==3.5.0,greenlet==0.4.14,keiyakusha==0.0.0,mccabe==0.6.1,monotonic==1.5,more-itertools==4.3.0,pathtools==0.1.2,pluggy==0.7.1,py==1.5.4,pycodestyle==2.3.1,pyflakes==1.6.0,pytest==3.7.1,pytest-django==3.4.1,pytest-pythonpath==0.7.2,pytz==2018.5,PyYAML==3.13,six==1.11.0,tox==3.2.1,tox-pip-extensions==1.3.0,unicode-slugify==0.1.3,Unidecode==1.0.22,venv-update==3.1.0,virtualenv==16.0.0,watchdog==0.8.3
py36 runtests: PYTHONHASHSEED='785840529'
py36 runtests: commands[0] | pytest
______________________________________________________ summary _______________________________________________________
  py36: commands succeeded
  py37: commands succeeded
  congratulations :)   
```

`detox` output without extension enabled:

```
GLOB sdist-make: /home/asday/code/src/github.com/asday/keiyakusha/setup.py
py37 inst-nodeps: /home/asday/code/src/github.com/asday/keiyakusha/.tox/dist/keiyakusha-0.0.0.zip
py36 inst-nodeps: /home/asday/code/src/github.com/asday/keiyakusha/.tox/dist/keiyakusha-0.0.0.zip
py37 runtests: PYTHONHASHSEED='3357464404'
py37 runtests: commands[0] | pytest
py36 runtests: PYTHONHASHSEED='3357464404'
py36 runtests: commands[0] | pytest
______________________________________________________ summary _______________________________________________________
  py36: commands succeeded
  py37: commands succeeded
  congratulations :)
```

**Comment by asottile** [comment]
> Was my expectation incorrect?

Your expectation was incorrect.  Because requirements can be specified in a code file (setup.py), determining the list of "things that should be installed" statically is impossible.  Because of this, `venv-update` uses a patched pip which attempts to avoid the network as much as possible to install things.  I'd suggest reading more about that [here](https://venv-update.readthedocs.io/en/master/#why)

The stacktrace you see from `detox` is a bug in `detox`.  It assumes that only [a hardcoded list of steps](https://github.com/tox-dev/detox/blob/2a6a36d7a75b6bff65c9e8ba2f54abfa01ff8295/detox/proc.py#L33-L34) exists and then [loops through all the steps](https://github.com/tox-dev/detox/blob/2a6a36d7a75b6bff65c9e8ba2f54abfa01ff8295/detox/proc.py#L46) and then [fails this assertion](https://github.com/tox-dev/detox/blob/2a6a36d7a75b6bff65c9e8ba2f54abfa01ff8295/detox/proc.py#L66).  `tox-pip-extensions` adds another step called ["bootstrap"](https://github.com/tox-dev/tox-pip-extensions/blob/31f126929d9a6c625342223050f04fd8d43c1bdd/tox_pip_extensions.py#L98) to install the necessary pip tools.

**Comment by Asday** [comment]
That's a shame.  The automatic synchronisation of environment to requirements is nice, but only when I change requirements, and all the rest of the time it just slows everything down.

Thanks for the thorough reply.

**Comment by asottile** [comment]
If you can solve the halting problem I'm all ears :)

**Comment by Asday** [comment]
My initial thought was "just let the user specify".

Establish a contract with the user, where they do something like specify the requirements files, and you only update the environments when those files change.

If stuff fails because they're bringing in a dependency elsewhere, then that's now on them.

It also means a user of _their_ library can glance at their `tox.ini` and see "aah ok, this is the absolute be all and end all source of truth requirements file(s)".

This is all speaking from absolute ignorance, though.  The closest I've looked at the code to do with _any_ of this is a cursory glance at the links you provided earlier.

**Comment by asottile** [comment]
Yeah the problem with manually specifying is users don't actually understand what is happening.

This project was aimed to be a drop-in tool for developers that _don't_ understand packaging (tox is supposed to make that easy, right?).  Requiring users to understand how `setup.py` and `requirements.txt` and `-r`, what causes a rebuild, what doesn't, and etc. etc. interact isn't simple.  And at the end of the day, the knowledge for handling those is encoded in implementation details of `pip`!

Requiring a user to additionally duplicate all that information again in a configuration files not only tedious but incredibly error prone.

Also the overhead you're referring to here should be ~at most a second or two for an already created venv (comparable to the `pip freeze` call).  The real place where venv-update shines is when things change (which is pretty often for applications where bumping requirements is commonplace).  In this case venv-update knows how to uninstall and install packages to get to the proper desired state without throwing away the entire virtualenv.

**Comment by Asday** [comment]
>Requiring a user to additionally duplicate all that information again in a configuration files not only tedious but incredibly error prone.

Possibly...  But my `tox.ini` specifies `deps = -rrequirements-dev.txt`.  In my entirely uneducated mind, it seems trivial to check whether that file has changed, and update environments if so.  If I also put `I_promise_my_deps_are_up_to_date = true`, then that would have me smiling on my way.

>Also the overhead you're referring to here should be ~at most a second or two for an already created venv 

It actually seems like quite a significant overhead.

Without the extension:

```
(env) ~/code/src/github.com/asday/keiyakusha $ time tox
GLOB sdist-make: /home/asday/code/src/github.com/asday/keiyakusha/setup.py
py36 inst-nodeps: /home/asday/code/src/github.com/asday/keiyakusha/.tox/dist/keiyakusha-0.0.0.zip
py36 installed: argh==0.26.2,atomicwrites==1.1.5,attrs==18.1.0,detox==0.12,Django==2.1,django-tables2==1.21.2,django-widget-tweaks==1.4.2,dnspython==1.15.0,eventlet==0.24.1,flake8==3.5.0,greenlet==0.4.14,keiyakusha==0.0.0,mccabe==0.6.1,monotonic==1.5,more-itertools==4.3.0,pathtools==0.1.2,pluggy==0.7.1,py==1.5.4,pycodestyle==2.3.1,pyflakes==1.6.0,pytest==3.7.1,pytest-django==3.4.1,pytest-pythonpath==0.7.2,pytz==2018.5,PyYAML==3.13,six==1.11.0,tox==3.2.1,tox-pip-extensions==1.3.0,unicode-slugify==0.1.3,Unidecode==1.0.22,venv-update==3.1.0,virtualenv==16.0.0,watchdog==0.8.3
py36 runtests: PYTHONHASHSEED='2856703926'
py36 runtests: commands[0] | pytest
================================================ test session starts =================================================
platform linux -- Python 3.6.6, pytest-3.7.1, py-1.5.4, pluggy-0.7.1
Django settings: config.settings (from ini file)
rootdir: /home/asday/code/src/github.com/asday/keiyakusha, inifile: tox.ini
plugins: pythonpath-0.7.2, django-3.4.1
collected 1 item                                                                                                     

tests/test_main.py .                                                                                           [100%]

============================================== 1 passed in 0.10 seconds ==============================================
py37 inst-nodeps: /home/asday/code/src/github.com/asday/keiyakusha/.tox/dist/keiyakusha-0.0.0.zip
py37 installed: argh==0.26.2,atomicwrites==1.1.5,attrs==18.1.0,detox==0.12,Django==2.1,django-tables2==1.21.2,django-widget-tweaks==1.4.2,dnspython==1.15.0,eventlet==0.24.1,flake8==3.5.0,greenlet==0.4.14,keiyakusha==0.0.0,mccabe==0.6.1,monotonic==1.5,more-itertools==4.3.0,pathtools==0.1.2,pluggy==0.7.1,py==1.5.4,pycodestyle==2.3.1,pyflakes==1.6.0,pytest==3.7.1,pytest-django==3.4.1,pytest-pythonpath==0.7.2,pytz==2018.5,PyYAML==3.13,six==1.11.0,tox==3.2.1,tox-pip-extensions==1.3.0,unicode-slugify==0.1.3,Unidecode==1.0.22,venv-update==3.1.0,virtualenv==16.0.0,watchdog==0.8.3
py37 runtests: PYTHONHASHSEED='2856703926'
py37 runtests: commands[0] | pytest
================================================ test session starts =================================================
platform linux -- Python 3.7.0, pytest-3.7.1, py-1.5.4, pluggy-0.7.1
Django settings: config.settings (from ini file)
rootdir: /home/asday/code/src/github.com/asday/keiyakusha, inifile: tox.ini
plugins: pythonpath-0.7.2, django-3.4.1
collected 1 item                                                                                                     

tests/test_main.py .                                                                                           [100%]

============================================== 1 passed in 0.09 seconds ==============================================
______________________________________________________ summary _______________________________________________________
  py36: commands succeeded
  py37: commands succeeded
  congratulations :)

real	0m5.797s
user	0m5.228s
sys	0m0.500s
```

With the extension:

```
(env) ~/code/src/github.com/asday/keiyakusha $ time tox
GLOB sdist-make: /home/asday/code/src/github.com/asday/keiyakusha/setup.py
py36 inst-nodeps: /home/asday/code/src/github.com/asday/keiyakusha/.tox/dist/keiyakusha-0.0.0.zip
py36 installed: argh==0.26.2,atomicwrites==1.1.5,attrs==18.1.0,detox==0.12,Django==2.1,django-tables2==1.21.2,django-widget-tweaks==1.4.2,dnspython==1.15.0,eventlet==0.24.1,flake8==3.5.0,greenlet==0.4.14,keiyakusha==0.0.0,mccabe==0.6.1,monotonic==1.5,more-itertools==4.3.0,pathtools==0.1.2,pluggy==0.7.1,py==1.5.4,pycodestyle==2.3.1,pyflakes==1.6.0,pytest==3.7.1,pytest-django==3.4.1,pytest-pythonpath==0.7.2,pytz==2018.5,PyYAML==3.13,six==1.11.0,tox==3.2.1,tox-pip-extensions==1.3.0,unicode-slugify==0.1.3,Unidecode==1.0.22,venv-update==3.1.0,virtualenv==16.0.0,watchdog==0.8.3
py36 bootstrap: venv-update>=2.1.3
GLOB sdist-make: /home/asday/code/src/github.com/asday/keiyakusha/setup.py
py36 installdeps: -rrequirements-dev.txt
py36 installed: argh==0.26.2,atomicwrites==1.1.5,attrs==18.1.0,detox==0.12,Django==2.1,django-tables2==2.0.0a5,django-widget-tweaks==1.4.2,dnspython==1.15.0,eventlet==0.24.1,flake8==3.5.0,greenlet==0.4.14,keiyakusha==0.0.0,mccabe==0.6.1,monotonic==1.5,more-itertools==4.3.0,pathtools==0.1.2,pluggy==0.7.1,py==1.5.4,pycodestyle==2.3.1,pyflakes==1.6.0,pytest==3.7.1,pytest-django==3.4.1,pytest-pythonpath==0.7.2,pytz==2018.5,PyYAML==3.13,six==1.11.0,tox==3.2.1,tox-pip-extensions==1.3.0,unicode-slugify==0.1.3,Unidecode==1.0.22,venv-update==3.1.0,virtualenv==16.0.0,watchdog==0.8.3
py36 runtests: PYTHONHASHSEED='2073751148'
py36 runtests: commands[0] | pytest
================================================ test session starts =================================================
platform linux -- Python 3.6.6, pytest-3.7.1, py-1.5.4, pluggy-0.7.1
Django settings: config.settings (from ini file)
rootdir: /home/asday/code/src/github.com/asday/keiyakusha, inifile: tox.ini
plugins: pythonpath-0.7.2, django-3.4.1
collected 1 item                                                                                                     

tests/test_main.py .                                                                                           [100%]

============================================== 1 passed in 0.10 seconds ==============================================
py37 inst-nodeps: /home/asday/code/src/github.com/asday/keiyakusha/.tox/dist/keiyakusha-0.0.0.zip
py37 installed: argh==0.26.2,atomicwrites==1.1.5,attrs==18.1.0,detox==0.12,Django==2.1,django-tables2==1.21.2,django-widget-tweaks==1.4.2,dnspython==1.15.0,eventlet==0.24.1,flake8==3.5.0,greenlet==0.4.14,keiyakusha==0.0.0,mccabe==0.6.1,monotonic==1.5,more-itertools==4.3.0,pathtools==0.1.2,pluggy==0.7.1,py==1.5.4,pycodestyle==2.3.1,pyflakes==1.6.0,pytest==3.7.1,pytest-django==3.4.1,pytest-pythonpath==0.7.2,pytz==2018.5,PyYAML==3.13,six==1.11.0,tox==3.2.1,tox-pip-extensions==1.3.0,unicode-slugify==0.1.3,Unidecode==1.0.22,venv-update==3.1.0,virtualenv==16.0.0,watchdog==0.8.3
py37 bootstrap: venv-update>=2.1.3
GLOB sdist-make: /home/asday/code/src/github.com/asday/keiyakusha/setup.py
py37 installdeps: -rrequirements-dev.txt
py37 installed: argh==0.26.2,atomicwrites==1.1.5,attrs==18.1.0,detox==0.12,Django==2.1,django-tables2==2.0.0a5,django-widget-tweaks==1.4.2,dnspython==1.15.0,eventlet==0.24.1,flake8==3.5.0,greenlet==0.4.14,keiyakusha==0.0.0,mccabe==0.6.1,monotonic==1.5,more-itertools==4.3.0,pathtools==0.1.2,pluggy==0.7.1,py==1.5.4,pycodestyle==2.3.1,pyflakes==1.6.0,pytest==3.7.1,pytest-django==3.4.1,pytest-pythonpath==0.7.2,pytz==2018.5,PyYAML==3.13,six==1.11.0,tox==3.2.1,tox-pip-extensions==1.3.0,unicode-slugify==0.1.3,Unidecode==1.0.22,venv-update==3.1.0,virtualenv==16.0.0,watchdog==0.8.3
py37 runtests: PYTHONHASHSEED='2073751148'
py37 runtests: commands[0] | pytest
================================================ test session starts =================================================
platform linux -- Python 3.7.0, pytest-3.7.1, py-1.5.4, pluggy-0.7.1
Django settings: config.settings (from ini file)
rootdir: /home/asday/code/src/github.com/asday/keiyakusha, inifile: tox.ini
plugins: pythonpath-0.7.2, django-3.4.1
collected 1 item                                                                                                     

tests/test_main.py .                                                                                           [100%]

============================================== 1 passed in 0.09 seconds ==============================================
______________________________________________________ summary _______________________________________________________
  py36: commands succeeded
  py37: commands succeeded
  congratulations :)

real	0m14.035s
user	0m12.412s
sys	0m1.108s
```

6 seconds to 14 seconds running a single test which does essentially nothing with `tox`.

The story with `detox` is a little better, going from 2.8 to 6.5 seconds.

Without the extension:

```
(env) ~/code/src/github.com/asday/keiyakusha $ time detox
GLOB sdist-make: /home/asday/code/src/github.com/asday/keiyakusha/setup.py
py37 inst-nodeps: /home/asday/code/src/github.com/asday/keiyakusha/.tox/dist/keiyakusha-0.0.0.zip
py36 inst-nodeps: /home/asday/code/src/github.com/asday/keiyakusha/.tox/dist/keiyakusha-0.0.0.zip
py36 runtests: PYTHONHASHSEED='1008767484'
py36 runtests: commands[0] | pytest
py37 runtests: PYTHONHASHSEED='1008767484'
py37 runtests: commands[0] | pytest
______________________________________________________ summary _______________________________________________________
  py36: commands succeeded
  py37: commands succeeded
  congratulations :)

real	0m2.845s
user	0m4.476s
sys	0m0.424s
```

With the extension:

```
(env) ~/code/src/github.com/asday/keiyakusha $ time detox
GLOB sdist-make: /home/asday/code/src/github.com/asday/keiyakusha/setup.py
py36 inst-nodeps: /home/asday/code/src/github.com/asday/keiyakusha/.tox/dist/keiyakusha-0.0.0.zip
py37 inst-nodeps: /home/asday/code/src/github.com/asday/keiyakusha/.tox/dist/keiyakusha-0.0.0.zip
py37 bootstrap: venv-update>=2.1.3
py36 bootstrap: venv-update>=2.1.3
Traceback (most recent call last):
  File "/home/asday/code/src/github.com/asday/keiyakusha/env/lib/python3.7/site-packages/eventlet/hubs/hub.py", line 460, in fire_timers
    timer()
  File "/home/asday/code/src/github.com/asday/keiyakusha/env/lib/python3.7/site-packages/eventlet/hubs/timer.py", line 59, in __call__
    cb(*args, **kw)
  File "/home/asday/code/src/github.com/asday/keiyakusha/env/lib/python3.7/site-packages/detox/proc.py", line 66, in _loopreport
    assert not ac2popenlist, ac2popenlist
AssertionError: {'bootstrap': [<eventlet.green.subprocess.Popen object at 0x7fc6b169cbe0>, <eventlet.green.subprocess.Popen object at 0x7fc6b169c780>]}
GLOB sdist-make: /home/asday/code/src/github.com/asday/keiyakusha/setup.py
GLOB sdist-make: /home/asday/code/src/github.com/asday/keiyakusha/setup.py
py37 installdeps: -rrequirements-dev.txt
py36 installdeps: -rrequirements-dev.txt
py37 installed: argh==0.26.2,atomicwrites==1.1.5,attrs==18.1.0,detox==0.12,Django==2.1,django-tables2==2.0.0a5,django-widget-tweaks==1.4.2,dnspython==1.15.0,eventlet==0.24.1,flake8==3.5.0,greenlet==0.4.14,keiyakusha==0.0.0,mccabe==0.6.1,monotonic==1.5,more-itertools==4.3.0,pathtools==0.1.2,pluggy==0.7.1,py==1.5.4,pycodestyle==2.3.1,pyflakes==1.6.0,pytest==3.7.1,pytest-django==3.4.1,pytest-pythonpath==0.7.2,pytz==2018.5,PyYAML==3.13,six==1.11.0,tox==3.2.1,tox-pip-extensions==1.3.0,unicode-slugify==0.1.3,Unidecode==1.0.22,venv-update==3.1.0,virtualenv==16.0.0,watchdog==0.8.3
py37 runtests: PYTHONHASHSEED='174879892'
py37 runtests: commands[0] | pytest
py36 installed: argh==0.26.2,atomicwrites==1.1.5,attrs==18.1.0,detox==0.12,Django==2.1,django-tables2==2.0.0a5,django-widget-tweaks==1.4.2,dnspython==1.15.0,eventlet==0.24.1,flake8==3.5.0,greenlet==0.4.14,keiyakusha==0.0.0,mccabe==0.6.1,monotonic==1.5,more-itertools==4.3.0,pathtools==0.1.2,pluggy==0.7.1,py==1.5.4,pycodestyle==2.3.1,pyflakes==1.6.0,pytest==3.7.1,pytest-django==3.4.1,pytest-pythonpath==0.7.2,pytz==2018.5,PyYAML==3.13,six==1.11.0,tox==3.2.1,tox-pip-extensions==1.3.0,unicode-slugify==0.1.3,Unidecode==1.0.22,venv-update==3.1.0,virtualenv==16.0.0,watchdog==0.8.3
py36 runtests: PYTHONHASHSEED='174879892'
py36 runtests: commands[0] | pytest
______________________________________________________ summary _______________________________________________________
  py36: commands succeeded
  py37: commands succeeded
  congratulations :)   

real	0m6.450s
user	0m10.844s
sys	0m1.000s
```

For context, I'm running `detox` with `watchdog` on every python file change, with the idea being that if I break a test, I'll know roughly as soon as I hit save.  The aim is to have the console go red before I can go and refresh my browser.  The immediacy of feedback leads to a very smooth-feeling workflow.

>The real place where venv-update shines is when things change 

For sure, it's faster than `--recreate`, which is why I'm keeping it.  My workflow for changing my dependencies now, though, is a bit clunky.  I update `requirements.txt`, then uncomment `tox_pip_extensions_ext_venv_update = true`, then run `detox` (usually by saving an open `.py` file), then recomment the line.

From the above, you'll see why I think it should be simple to automate the process - I'm already telling it when to or not to short-circuit.  It's entirely possible I'm a huge idiot and there's something simple I'm missing somewhere, of course.

**Comment by asottile** [comment]
Your measurements double the overhead since you have two environments.  The `detox` values aren't necessarily valid because `detox` is crashing during the installation process.  Assuming they were consistent that's ~3.5 seconds which isn't all that much (and most of it is probably invoking `setup.py`!).

> Possibly...  But my `tox.ini` specifies `deps = -rrequirements-dev.txt`.  In my entirely uneducated mind, it seems trivial to check whether that file has changed, and update environments if so.  If I also put `I_promise_my_deps_are_up_to_date = true`, then that would have me smiling on my way.

What if that `requirements.txt` contains `-r requirementsother.txt`? Or if your `setup.py` does `open('requirements.in')` to retrieve its requirements (two very very common patterns).  Do we now teach `tox` how to traverse requirements files?  What if that path is a symlink?  What if it is on a network storage?  What if it's a URL?

***

Anyway, the problem is not a simple one and you don't have to use the extension -- it is working as intended however 😄

**Comment by Asday** [comment]
>Your measurements double the overhead since you have two environments.

Of course!  That's why I have tox.  I'll have 3 environments once Python 3.8 comes out, and I'd have 4 if 3.5 supported f-strings :D

>What if that `requirements.txt` contains `-r requirementsother.txt`? 

Well then I should have put the following in `tox.ini`:

```ini
deps =
    -rrequirements.txt
    -rrequirementsother.txt
```

>Or if your `setup.py` does `open('requirements.in')` to retrieve its requirements

Not listed in `deps`?  Not [imaginary tox extension]'s problem!  This is what I mean by putting the honus on the user.  If the user wants a better experience, they have to put the teensiest bit of effort in.

>Anyway, the problem is not a simple one and you don't have to use the extension -- it is working as intended however :smile:

Yeah for sure.  Like I said, the uncomment-comment dance with the ini file is still faster than `--recreate`, so I'm gonna keep using it.  Like I said, I'm entirely uneducated and just throwing ideas around.

Thanks for your time, have a good week.  :D

**Comment by asottile** [comment]
> and I'd have 4 if 3.5 supported f-strings :D

I'm not seriously suggesting it, but have you checked out https://github.com/asottile/future-fstrings :P

<blockquote><img src="https://avatars3.githubusercontent.com/u/1810591?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/asottile/future-fstrings">asottile/future-fstrings</a></strong></div><div>future-fstrings - A backport of fstrings to python<3.6</div></blockquote>
