### ISSUE TITLE
Tox fails to build environment if requirement appears in requirements-bootstrap.txt and requirements.txt

### ISSUE THREAD

**Issue by ipwnponies** [tox-dev/tox-pip-extensions#24]
When the same requirements appear in `requirements-bootstrap.txt` and `requirements.txt`, tox will fail to build with "Double requirements given".

Continuing the conversation from yelp/venv-update#225. This issue only reproduces with tox + tox-pip-extensions.

### Repro
Using `wheel` as our guinea pig here. It's pinned in bootstrap.txt but maybe our application has dependency on it, at a different version.
```
tail requirements* tox.ini                                                                                                 Wed Mar 20 12:14:04 2019
==> requirements-bootstrap.txt <==
pip==18.1
pip-custom-platform==0.5.0
pymonkey==0.3.0
venv-update==3.2.2
wheel==0.26.0

==> requirements.txt <==
wheel

==> tox.ini <==
[tox]
skipsdist = true
tox_pip_extensions_ext_pip_custom_platform = true
tox_pip_extensions_ext_venv_update = true

[testenv]
deps =
    -rrequirements.txt

$ virtualenv toxenv; and toxenv/bin/pip install tox==3.7.0 tox-pip-extensions==1.5.0; and toxenv/bin/tox
Using real prefix '/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7'
New python executable in /Users/jngu/venv-update-issue/toxenv/bin/python3.7
Also creating executable in /Users/jngu/venv-update-issue/toxenv/bin/python
Installing setuptools, pip, wheel...
done.
Collecting tox==3.7.0
  Using cached https://files.pythonhosted.org/packages/4a/bd/50cd91221508db5bb66e211ac327d0da4a5db6d0db5ad35d6fbf1e4af5dc/tox-3.7.0-py2.py3-none-any.whl
Collecting tox-pip-extensions==1.5.0
  Using cached https://files.pythonhosted.org/packages/30/be/f652b33d7c6e50e01b94fee2f0864743e422330fb4788084765a91d30cba/tox_pip_extensions-1.5.0-py2.py3-none-any.whl
Collecting filelock<4,>=3.0.0 (from tox==3.7.0)
  Using cached https://files.pythonhosted.org/packages/d7/ca/3c74396a9ed8a4cfab5459800edeef9a1269591cb21f5a49bd71a49c5fa2/filelock-3.0.10-py3-none-any.whl
Collecting pluggy<1,>=0.3.0 (from tox==3.7.0)
  Using cached https://files.pythonhosted.org/packages/84/e8/4ddac125b5a0e84ea6ffc93cfccf1e7ee1924e88f53c64e98227f0af2a5f/pluggy-0.9.0-py2.py3-none-any.whl
Collecting toml>=0.9.4 (from tox==3.7.0)
  Using cached https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
Collecting virtualenv>=1.11.2 (from tox==3.7.0)
  Using cached https://files.pythonhosted.org/packages/33/5d/314c760d4204f64e4a968275182b7751bd5c3249094757b39ba987dcfb5a/virtualenv-16.4.3-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=30.0.0 in ./toxenv/lib/python3.7/site-packages (from tox==3.7.0) (40.8.0)
Collecting py<2,>=1.4.17 (from tox==3.7.0)
  Using cached https://files.pythonhosted.org/packages/76/bc/394ad449851729244a97857ee14d7cba61ddb268dce3db538ba2f2ba1f0f/py-1.8.0-py2.py3-none-any.whl
Collecting six<2,>=1.0.0 (from tox==3.7.0)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: filelock, pluggy, toml, virtualenv, py, six, tox, tox-pip-extensions
Successfully installed filelock-3.0.10 pluggy-0.9.0 py-1.8.0 six-1.12.0 toml-0.10.0 tox-3.7.0 tox-pip-extensions-1.5.0 virtualenv-16.4.3
python installed: distro==1.4.0,pip-custom-platform==0.5.0,pymonkey==0.3.0,venv-update==3.2.2
python bootstrap: -r/Users/jngu/venv-update-issue/requirements-bootstrap.txt
WARNING: Discarding $PYTHONPATH from environment, to override specify PYTHONPATH in 'passenv' in your configuration.
python installdeps: -rrequirements.txt
ERROR: invocation failed (exit code 1), logfile: /Users/jngu/venv-update-issue/.tox/python/log/python-8.log
ERROR: actionid: python
msg: tox-pip-extensions
cmdargs: '/Users/jngu/venv-update-issue/.tox/python/bin/pymonkey pip-custom-platform -- pip-faster install -rrequirements.txt -r/Users/jngu/venv-update-issue/requirements-bootstrap.txt --prune'

Double requirement given: wheel==0.26.0 (from -r /Users/jngu/venv-update-issue/requirements-bootstrap.txt (line 5)) (already in wheel (from -r requirements.txt (line 1)), name='wheel')
You are using pip version 18.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Traceback (most recent call last):
  File "toxenv/bin/tox", line 10, in <module>
    sys.exit(cmdline())
  File "/Users/jngu/venv-update-issue/toxenv/lib/python3.7/site-packages/tox/session.py", line 47, in cmdline
    main(args)
  File "/Users/jngu/venv-update-issue/toxenv/lib/python3.7/site-packages/tox/session.py", line 54, in main
    retcode = build_session(config).runcommand()
  File "/Users/jngu/venv-update-issue/toxenv/lib/python3.7/site-packages/tox/session.py", line 467, in runcommand
    return self.subcommand_test()
  File "/Users/jngu/venv-update-issue/toxenv/lib/python3.7/site-packages/tox/session.py", line 590, in subcommand_test
    self.run_sequential()
  File "/Users/jngu/venv-update-issue/toxenv/lib/python3.7/site-packages/tox/session.py", line 609, in run_sequential
    self.runtestenv(venv)
  File "/Users/jngu/venv-update-issue/toxenv/lib/python3.7/site-packages/tox/session.py", line 726, in runtestenv
    self.hook.tox_runtest_pre(venv=venv)
  File "/Users/jngu/venv-update-issue/toxenv/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/jngu/venv-update-issue/toxenv/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/jngu/venv-update-issue/toxenv/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/jngu/venv-update-issue/toxenv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/jngu/venv-update-issue/toxenv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/jngu/venv-update-issue/toxenv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/jngu/venv-update-issue/toxenv/lib/python3.7/site-packages/tox_pip_extensions.py", line 146, in tox_runtest_pre
    _install(venv, action, 'installdeps', venv.get_resolved_dependencies())
  File "/Users/jngu/venv-update-issue/toxenv/lib/python3.7/site-packages/tox_pip_extensions.py", line 83, in _install
    venv._install(deps, action=action)
  File "/Users/jngu/venv-update-issue/toxenv/lib/python3.7/site-packages/tox/venv.py", line 418, in _install
    self.run_install_command(packages=packages, options=options, action=action)
  File "/Users/jngu/venv-update-issue/toxenv/lib/python3.7/site-packages/tox/venv.py", line 372, in run_install_command
    redirect=self.session.report.verbosity < 2,
  File "/Users/jngu/venv-update-issue/toxenv/lib/python3.7/site-packages/tox/venv.py", line 527, in _pcall
    args, cwd=cwd, env=env, redirect=redirect, ignore_ret=ignore_ret, returnout=returnout
  File "/Users/jngu/venv-update-issue/toxenv/lib/python3.7/site-packages/tox/session.py", line 251, in popen
    raise tox.exception.InvocationError("{} (see {})".format(invoked, outpath), ret)
tox.exception.InvocationError: InvocationError for command /Users/jngu/venv-update-issue/.tox/python/bin/pymonkey pip-custom-platform -- pip-faster install -rrequirements.txt -r/Users/jngu/venv-update-issue/requirements-bootstrap.txt --prune (see /Users/jngu/venv-update-issue/.tox/python/log/python-8.log) (exited with code 1)
```

### Workaround
If the requirement is specified exactly the same in both `requirements-bootstrap.txt` and `requirements.txt`, then there's no issue and tox can continue.
i.e if the requirement is strictly pinned to the same version in both.
Playing around with it, it's seems to either an exact string comparison or using the same pip version specifier (>,<=,~,!).

**Comment by asottile** [comment]
You have a conflict between `requirements-bootstrap.txt` and your final depdendncies, therefore this is invalid

**Comment by ipwnponies** [comment]
`venv-update` handles this correctly by first installing bootstrap requirements, then `pip install --upgrade` to reinstall the target dependencies. How come this doesn't behave similarly with `tox_pip_extensions_ext_venv_update = true`?

**Comment by asottile** [comment]
for speed, you'd have flux in and out of those requirements on every run

**Comment by ipwnponies** [comment]
I tested this (out of curiousity). `venv-update` on an unchanged requirements ~3s and each changed requirement added 1 additional second (33% per dependency).

Thanks @asottile for the quick response!
