### ISSUE TITLE
crash while creating `.tox/.tox` bootstrap environment

### ISSUE THREAD

**Issue by asottile** [tox-dev/tox-pip-extensions#27]
```ini
[tox]
requires =
    astpretty

[testenv]
commands = python --version
```

```
$ tox -e py37
.tox create: /home/asottile/workspace/tox/t/.tox/.tox
Traceback (most recent call last):
  File "/home/asottile/bin/tox", line 10, in <module>
    sys.exit(cmdline())
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/tox/session/__init__.py", line 68, in main
    exit_code = session.runcommand()
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/tox/session/__init__.py", line 182, in runcommand
    return provision_tox(provision_tox_venv, self.config.args)
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/tox/session/commands/provision.py", line 10, in provision_tox
    ensure_meta_env_up_to_date(provision_venv)
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/tox/session/commands/provision.py", line 23, in ensure_meta_env_up_to_date
    if provision_venv.setupenv():
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/tox/venv.py", line 594, in setupenv
    status = self.update(action=action)
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/tox/venv.py", line 257, in update
    self.hook.tox_testenv_install_deps(action=action, venv=self)
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/tox_pip_extensions.py", line 104, in tox_testenv_install_deps
    extensions, bootstrap_deps = config.pip_extensions
AttributeError: 'Config' object has no attribute 'pip_extensions'
```

**Comment by asottile** [comment]
@gaborbernat any chance this'll be solved by the rewrite? seems plugin initialization both happens too early and not early enough

**Comment by gaborbernat** [comment]
I think might be ok post rewrite, but we'll need to check.
